# Generated by Django 6.0.5 on 2026-05-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roles", "0002_alter_role_name"),
        ("users", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="roles",
            field=models.ManyToManyField(to="roles.role"),
        ),
    ]
