# Generated by Django 6.0.5 on 2026-05-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_recoverpassword"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NONE", "None"),
                    ("WAITING_FOR_NEW_PASSWD", "Waiting for new password"),
                ],
                default="NONE",
                max_length=22,
                null=True,
            ),
        ),
    ]
