# Generated by Django 6.0.5 on 2026-05-25 21:33

import django.core.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=users.models.client_profile_image_directory_path,
                validators=[django.core.validators.validate_image_file_extension],
            ),
        ),
    ]
