# Generated by Django 6.0.5 on 2026-06-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("roles", "0002_alter_role_name"),
        ("users", "0011_user_session_version"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_superuser", False), ("is_active", True), _connector="OR"
                ),
                name="superuser_must_be_active",
                violation_error_message="Superuser cannot be inactive.",
            ),
        ),
    ]
