# Generated by Django 6.0.5 on 2026-06-15 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0001_initial"),
        ("users", "0013_alter_user_superuser_must_be_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="branches.branch",
            ),
        ),
    ]
