# Generated by Django 6.0.5 on 2026-06-22 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_user_branch"),
    ]

    operations = [
        migrations.CreateModel(
            name="CashbackHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("EARNED", "Earned"),
                            ("SPENT", "Spent"),
                            ("RESERVED", "Reserved"),
                            ("RELEASED", "Released"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "released_with",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.cashbackhistory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cashback_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="check_cashback_history_amount_gt_zero",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("released_with__isnull", True),
                            ("type", "RESERVED"),
                            _connector="OR",
                        ),
                        name="released_with_only_for_reserved_type",
                    ),
                ],
            },
        ),
    ]
