services:
  backend:
    build: .
    expose:
      - 80
    env_file:
      - ./.env
    restart: always

  celery:
    build: .
    restart: always
    command: ["celery", "-A", "config", "worker", "--loglevel=ERROR"]
    env_file:
      - ./.env
    depends_on:
      - backend
    networks:
      - dokploy-network
      - default

  celery-beat:
    build: .
    restart: always
    command: ["celery", "-A", "config", "beat", "--loglevel=ERROR"]
    env_file:
      - ./.env
    depends_on:
      - backend
    networks:
      - dokploy-network
      - default
