# Generated by Django 6.0.5 on 2026-07-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="is_pickup_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
