# Generated by Django 6.0.5 on 2026-07-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0003_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50, unique=True, verbose_name="name"),
        ),
    ]
