# Generated by Django 6.0.5 on 2026-05-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                db_index=True, max_length=50, unique=True, verbose_name="name"
            ),
        ),
    ]
